language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
before_script:
  - psql -c 'create database justdoit_test;' -U postgres
script:
  - bin/rails db:setup RAILS_ENV=test
  - bundle exec rspec
addons:
  code_climate:
    repo_token: ENV["codeclimate_repo_token"]
after_success:
  - bundle exec codeclimate-test-reporter
